<template>
    <div>
        <h4 class="text-center text-uppercase my-4">Terms of Use of Sparktrend.net</h4>
        <h5 class="mt-4 mb-2">Terms and Conditions</h5>
        <p class="text-justify">These terms and conditions ("Terms", "Agreement") are an agreement between Sparktrend.net ("Sparktrend", "us", "we" or "our") and you ("User", "you" or "your"). This Agreement sets forth the general terms and conditions of your use of the http://www.sparktrend.net website and any of its products or services (collectively, "Website" or "Services"). The Platform is provided solely (the "Permitted Use ") to: (1) assist you in collecting and processing information about the various types of campaign opportunities and Influencers available on the Platform. This includes but not limited to Influencer Profiles, Influencer descriptions and price ranges for each Influencer; (2) allow you to post the reviews of Influencers and Advertisers; (3) allow you to post your Campaign information and also respond to any Campaign opportunities; (4) Smoothen communication with Influencers or Advertisers with the sole purpose of entering into a Campaign Agreement; and (5) Smoothen the transfer of payments to the Influencer from the Advertiser under a Campaign Agreement.</p>
        <h5 class="mt-4 mb-2">Use of the platform</h5>
        <p class="text-justify">You must be at least 13 years of age to use this Website. By using this Website and by agreeing to this Agreement you warrant and represent that you are at least 13 years of age. If you create an account on the Website, you are responsible for maintaining the security of your account and you are fully responsible for all activities that occur under the account and any other actions taken in connection with it. We may monitor and review new accounts before you may sign in and use our Services. Providing false contact information of any kind may result in the termination of your account. You must immediately notify us of any unauthorized uses of your account or any other breaches of security. We will not be liable for any acts or omissions by you, including any damages of any kind incurred as a result of such acts or omissions. We may suspend, disable, or delete your account (or any part thereof) if we determine that you have violated any provision of this Agreement or that your conduct or content would tend to damage our reputation and goodwill. If we delete your account for the foregoing reasons, you may not re-register for our Services. We may block your email address and Internet protocol address to prevent further registration.</p>
        <h5 class="mt-4 mb-2">License Grants</h5>
        <p class="text-justify">In accordance to these Terms of Use, Sparktrend grants you a personal, revocable, non-exclusive and non-transferable license during the Term of usage of our platform.
            In turn, you hereby grant to Sparktrend a perpetual, transferrable, royalty-free, irrevocable, worldwide and fully paid-up license to access, gather, hold and process any information that (1) you input into the Platform, or (2) we gather from your local computer system or from third-parties with your permission.
        </p>
        <h5 class="mt-4 mb-2">Terms and Termination</h5>
        <p class="text-justify">Sparktrend fully reserves the right to terminate your account at will without any prior notice to the user. On the other hand, where you decide to cancel or terminate your Account with us, kindly send us an email to Sparktrend@hotmail.net and we will abruptly cancel same. Upon the cancellation, discontinuation or termination of your Account, all provisions of these Terms of Use which by their nature should survive will survive. This includes but not limited to dispute resolution provisions, limitations of liability, warranty disclaimers and ownership provisions. </p>
        <h5 class="mt-4 mb-2">Privacy Policy</h5>
        <p class="text-justify">Kindly visit our <router-link to="/policy">Privacy Policy Page</router-link> to review our current Privacy Policy which contains important information about our practices in collecting, storing, using and disclosing your personal information, and which is hereby incorporated into and forms a part of these Terms of Use.</p>
        <h5 class="mt-4 mb-2">Unlawful or Prohibited Use</h5>
        <p class="text-justify">In addition to other terms as set forth in the Agreement, you are prohibited from using the Website or its Content: (a) for any unlawful purpose; (b) to solicit others to perform or participate in any unlawful acts; (c) to violate any international, federal, provincial or state regulations, rules, laws, or local ordinances; (d) to infringe upon or violate our intellectual property rights or the intellectual property rights of others; (e) to harass, abuse, insult, harm, defame, slander, disparage, intimidate, or discriminate based on gender, sexual orientation, religion, ethnicity, race, age, national origin, or disability; (f) to submit false or misleading information; (g) to upload or transmit viruses or any other type of malicious code that will or may be used in any way that will affect the functionality or operation of the Service or of any related website, other websites, or the Internet; (h) to collect or track the personal information of others; (i) to spam, phish, pretext, spider, crawl, or scrape; (j) for any obscene or immoral purpose; or (k) to interfere with or circumvent the security features of the Service or any related website, other websites, or the Internet. We reserve the right to terminate your use of the Service or any related website for violating any of the prohibited uses.</p>
        <h5 class="mt-4 mb-2">Third Pary Websites</h5>
        <p class="text-justify">Although this Website may link to other websites, we are not, directly or indirectly, implying any approval, association, sponsorship, endorsement, or affiliation with any linked website, unless specifically stated herein. We are not responsible for examining or evaluating, and we do not warrant the offerings of, any businesses or individuals or the content of their websites. We do not assume any responsibility or liability for the actions, products, services, and content of any other third-parties. You should carefully review the legal statements and other conditions of use of any website which you access through a link from this Website. Your linking to any other off-site websites is at your own risk.</p>
        <h5 class="mt-4 mb-2">Communications Not Confidential</h5>
        <p class="text-justify">Sparktrend does not in any way whatsoever guarantee the confidentiality of any communications made by you through the Platform. Although Sparktrend generally adheres to the accepted industry practices in securing the transmission of data to, from and through the Platform, you understand, agree and acknowledge that Sparktrend cannot and does not guarantee the security of data transmitted over the Internet or public networks in connection with your use of the Platform or any Campaigns.</p>
        <h5 class="mt-4 mb-2">Disclaimer and Limitation of Liability</h5>
        <p class="text-justify">To the fullest extent permitted by applicable law, in no event will Sparktrend, its affiliates, officers, directors, employees, agents, suppliers or licensors be liable to any person for (a): any indirect, incidental, special, punitive, cover or consequential damages (including, without limitation, damages for lost profits, revenue, sales, goodwill, use of content, impact on business, business interruption, loss of anticipated savings, loss of business opportunity) however caused, under any theory of liability, including, without limitation, contract, tort, warranty, breach of statutory duty, negligence or otherwise, even if Sparktrend has been advised as to the possibility of such damages or could have foreseen such damages. To the maximum extent permitted by applicable law, the aggregate liability of Sparktrend and its affiliates, officers, employees, agents, suppliers and licensors, relating to the services will be limited to an amount greater of one dollar or any amounts actually paid in cash by you to Sparktrend for the prior one month period prior to the first event or occurrence giving rise to such liability. The limitations and exclusions also apply if this remedy does not fully compensate you for any losses or fails of its essential purpose.</p>
        <h5 class="mt-4 mb-2">Indemnification</h5>
        <p class="text-justify">You agree to indemnify and hold Sparktrend and its affiliates, directors, officers, employees, and agents harmless from and against any liabilities, losses, damages or costs, including reasonable attorneys' fees, incurred in connection with or arising from any third-party allegations, claims, actions, disputes, or demands asserted against any of them as a result of or relating to your Content, your use of the Website or Services or any wilful misconduct on your part.</p>
        <h5 class="mt-4 mb-2">Entire Agreement, Waiver and Severability</h5>
        <p class="text-justify">All rights and restrictions contained in this Agreement may be exercised and shall be applicable and binding only to the extent that they do not violate any applicable laws and are intended to be limited to the extent necessary so that they will not render this Agreement illegal, invalid or unenforceable. If any provision or portion of any provision of this Agreement shall be held to be illegal, invalid or unenforceable by a court of competent jurisdiction, it is the intention of the parties that the remaining provisions or portions thereof shall constitute their agreement with respect to the subject matter hereof, and all such remaining provisions or portions thereof shall remain in full force and effect.</p>
        <h5 class="mt-4 mb-2">Changes and amendments</h5>
        <p class="text-justify">We reserve the right to modify this Agreement or its policies relating to the Website or Services at any time, effective upon posting of an updated version of this Agreement on the Website. When we do, we will revise the updated date at the bottom of this page. Continued use of the Website after any such changes shall constitute your consent to such changes.</p>
        <h5 class="mt-4 mb-2">Acceptance of these terms</h5>
        <p class="text-justify">You acknowledge that you have read this Agreement and agree to all its terms and conditions. By using the Website or its Services you agree to be bound by this Agreement. If you do not agree to abide by the terms of this Agreement, you are not authorized to use or access the Website and its Services.</p>
        <h5 class="mt-4 mb-2">Contacting Us</h5>
        <p class="text-justify">If you would like to contact us to understand more about this Agreement or wish to contact us concerning any matter relating to it, you may send an email to <a href="mailto:sparktrend@hotmail.net">sparktrend@hotmail.net</a></p>
    </div>
</template>
<script>
    export default {

    }
</script>